### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by clairekrogers** [bryanng412/ChillSound#2]
* Why does a song have a user_id?  Is this the uploader or the artist?
* What does song:archived mean?
* Playlist:description column needs to be type text, not string
* Comments table needs a column to hold the text of the comment 
* Why does users have a description column?

**Comment by bryanng412** [comment]
Song's user_id is its uploader. Added artist string to differentiate
archived is nothing. Removed
changed playlist type to text
added type text content to comments table
Users may want to put a little description about themselves that is displayed on show page eg: I love house music!
